/**
 * Auto-generated CLI Command: maestro processes incidents
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.766Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../../utils/sdk-client.js';
import { formatOutput } from '../../../utils/output-formatter.js';
import { track } from '../../../telemetry/index.js';

export default class Incidents extends Command {
  static description = "Get incidents for a specific process";

  static examples = [
    'uipath maestro processes incidents --process-key "example" --folder-key "example"'
  ];

  static flags = {
        'process-key': Flags.string({
      description: "processKey parameter",
      required: true,
    }),
    'folder-key': Flags.string({
      description: "folderKey parameter",
      required: true,
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('maestro processes.incidents')
  async run(): Promise<void> {
    const { flags } = await this.parse(Incidents);
    const spinner = ora('Executing maestro processes incidents...').start();

    try {
      const client = await getSDKClient();
      const { 'folder-id': folderId, output, ...data } = flags;
      const result = await client.maestro.processes.getIncidents(data as any);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
