// AUTO-GENERATED by scripts/generate-manifests.mjs — do not edit.
import type { VersionManifest } from '../types/manifest';

export interface SdkModule {
  [exportName: string]: unknown;
}

export interface VersionEntry {
  manifest: () => Promise<VersionManifest>;
  core: () => Promise<SdkModule>;
  modules: Record<string, () => Promise<SdkModule>>;
}

function mod(loader: () => Promise<object>): () => Promise<SdkModule> {
  return () => loader().then((m) => m as SdkModule);
}

export const SDK_VERSIONS: Record<string, VersionEntry> = {
  '1.5.5': {
    manifest: () => import('../manifests/1.5.5.json').then((m) => m.default as VersionManifest),
    core: mod(() => import('sdk-v1_5_5/core')),
    modules: {
      'entities': mod(() => import('sdk-v1_5_5/entities')),
      'tasks': mod(() => import('sdk-v1_5_5/tasks')),
      'assets': mod(() => import('sdk-v1_5_5/assets')),
      'jobs': mod(() => import('sdk-v1_5_5/jobs')),
      'attachments': mod(() => import('sdk-v1_5_5/attachments')),
      'queues': mod(() => import('sdk-v1_5_5/queues')),
      'buckets': mod(() => import('sdk-v1_5_5/buckets')),
      'processes': mod(() => import('sdk-v1_5_5/processes')),
      'cases': mod(() => import('sdk-v1_5_5/cases')),
      'maestro-processes': mod(() => import('sdk-v1_5_5/maestro-processes')),
      'conversational-agent': mod(() => import('sdk-v1_5_5/conversational-agent')),
      'feedback': mod(() => import('sdk-v1_5_5/feedback')),
      'agent-memory': mod(() => import('sdk-v1_5_5/agent-memory')),
      'traces': mod(() => import('sdk-v1_5_5/traces')),
      'orchestrator-du-module': mod(() => import('sdk-v1_5_5/orchestrator-du-module')),
      'agents': mod(() => import('sdk-v1_5_5/agents')),
      'governance': mod(() => import('sdk-v1_5_5/governance')),
      'notifications': mod(() => import('sdk-v1_5_5/notifications')),
    },
  },
  '1.4.2': {
    manifest: () => import('../manifests/1.4.2.json').then((m) => m.default as VersionManifest),
    core: mod(() => import('sdk-v1_4_2/core')),
    modules: {
      'entities': mod(() => import('sdk-v1_4_2/entities')),
      'tasks': mod(() => import('sdk-v1_4_2/tasks')),
      'assets': mod(() => import('sdk-v1_4_2/assets')),
      'jobs': mod(() => import('sdk-v1_4_2/jobs')),
      'attachments': mod(() => import('sdk-v1_4_2/attachments')),
      'queues': mod(() => import('sdk-v1_4_2/queues')),
      'buckets': mod(() => import('sdk-v1_4_2/buckets')),
      'processes': mod(() => import('sdk-v1_4_2/processes')),
      'cases': mod(() => import('sdk-v1_4_2/cases')),
      'maestro-processes': mod(() => import('sdk-v1_4_2/maestro-processes')),
      'conversational-agent': mod(() => import('sdk-v1_4_2/conversational-agent')),
      'feedback': mod(() => import('sdk-v1_4_2/feedback')),
      'agent-memory': mod(() => import('sdk-v1_4_2/agent-memory')),
      'traces': mod(() => import('sdk-v1_4_2/traces')),
      'orchestrator-du-module': mod(() => import('sdk-v1_4_2/orchestrator-du-module')),
      'agents': mod(() => import('sdk-v1_4_2/agents')),
      'governance': mod(() => import('sdk-v1_4_2/governance')),
    },
  },
  '1.3.11': {
    manifest: () => import('../manifests/1.3.11.json').then((m) => m.default as VersionManifest),
    core: mod(() => import('sdk-v1_3_11/core')),
    modules: {
      'entities': mod(() => import('sdk-v1_3_11/entities')),
      'tasks': mod(() => import('sdk-v1_3_11/tasks')),
      'assets': mod(() => import('sdk-v1_3_11/assets')),
      'jobs': mod(() => import('sdk-v1_3_11/jobs')),
      'attachments': mod(() => import('sdk-v1_3_11/attachments')),
      'queues': mod(() => import('sdk-v1_3_11/queues')),
      'buckets': mod(() => import('sdk-v1_3_11/buckets')),
      'processes': mod(() => import('sdk-v1_3_11/processes')),
      'cases': mod(() => import('sdk-v1_3_11/cases')),
      'maestro-processes': mod(() => import('sdk-v1_3_11/maestro-processes')),
      'conversational-agent': mod(() => import('sdk-v1_3_11/conversational-agent')),
      'feedback': mod(() => import('sdk-v1_3_11/feedback')),
      'traces': mod(() => import('sdk-v1_3_11/traces')),
    },
  },
  '1.2.2': {
    manifest: () => import('../manifests/1.2.2.json').then((m) => m.default as VersionManifest),
    core: mod(() => import('sdk-v1_2_2/core')),
    modules: {
      'entities': mod(() => import('sdk-v1_2_2/entities')),
      'tasks': mod(() => import('sdk-v1_2_2/tasks')),
      'assets': mod(() => import('sdk-v1_2_2/assets')),
      'jobs': mod(() => import('sdk-v1_2_2/jobs')),
      'attachments': mod(() => import('sdk-v1_2_2/attachments')),
      'queues': mod(() => import('sdk-v1_2_2/queues')),
      'buckets': mod(() => import('sdk-v1_2_2/buckets')),
      'processes': mod(() => import('sdk-v1_2_2/processes')),
      'cases': mod(() => import('sdk-v1_2_2/cases')),
      'maestro-processes': mod(() => import('sdk-v1_2_2/maestro-processes')),
      'conversational-agent': mod(() => import('sdk-v1_2_2/conversational-agent')),
    },
  },
  '1.1.3': {
    manifest: () => import('../manifests/1.1.3.json').then((m) => m.default as VersionManifest),
    core: mod(() => import('sdk-v1_1_3/core')),
    modules: {
      'entities': mod(() => import('sdk-v1_1_3/entities')),
      'tasks': mod(() => import('sdk-v1_1_3/tasks')),
      'assets': mod(() => import('sdk-v1_1_3/assets')),
      'queues': mod(() => import('sdk-v1_1_3/queues')),
      'buckets': mod(() => import('sdk-v1_1_3/buckets')),
      'processes': mod(() => import('sdk-v1_1_3/processes')),
      'cases': mod(() => import('sdk-v1_1_3/cases')),
      'maestro-processes': mod(() => import('sdk-v1_1_3/maestro-processes')),
      'conversational-agent': mod(() => import('sdk-v1_1_3/conversational-agent')),
    },
  },
  '1.0.0': {
    manifest: () => import('../manifests/1.0.0.json').then((m) => m.default as VersionManifest),
    core: mod(() => import('sdk-v1_0_0/core')),
    modules: {
      'entities': mod(() => import('sdk-v1_0_0/entities')),
      'tasks': mod(() => import('sdk-v1_0_0/tasks')),
      'assets': mod(() => import('sdk-v1_0_0/assets')),
      'queues': mod(() => import('sdk-v1_0_0/queues')),
      'buckets': mod(() => import('sdk-v1_0_0/buckets')),
      'processes': mod(() => import('sdk-v1_0_0/processes')),
      'cases': mod(() => import('sdk-v1_0_0/cases')),
      'maestro-processes': mod(() => import('sdk-v1_0_0/maestro-processes')),
    },
  },
};

export const VERSION_LIST = Object.keys(SDK_VERSIONS);
