sonar.projectKey=UiPath_uipath-typescript
sonar.organization=uipath
sonar.projectName=uipath-typescript

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/samples/**,**/*.d.ts,**/*.config.*
sonar.coverage.exclusions=**/index.ts,**/*.d.ts,**/*.config.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage-integration/lcov.info

sonar.test.inclusions=tests/**/*.ts
sonar.scm.provider=git
