sonar.projectKey=UiPath_uipath-typescript
sonar.organization=uipath
sonar.projectName=uipath-typescript

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/samples/**,**/*.d.ts,**/*.config.*,**/index.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage-integration/lcov.info

sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.integration.test.ts
