/**
 * Auto-generated CLI Command: buckets get-file-metadata
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.766Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../utils/sdk-client.js';
import { formatOutput } from '../../utils/output-formatter.js';
import { track } from '../../telemetry/index.js';

export default class GetFileMetadata extends Command {
  static description = "Gets metadata for files in a bucket with optional filtering and pagination\n\nThe method returns either:\n- A NonPaginatedResponse with items array (when no pagination parameters are provided)\n- A PaginatedResponse with navigation cursors (when any pagination parameter is provided)";

  static examples = [
    'uipath buckets get-file-metadata --bucket-id "123" --folder-id "123"'
  ];

  static flags = {
        'bucket-id': Flags.integer({
      description: "The ID of the bucket to get file metadata from\n   *",
      required: true,
    }),
    'folder-id': Flags.integer({
      description: "Required folder ID for organization unit context\n   *",
      required: true,
    }),
    'options': Flags.string({
      description: "Optional parameters for filtering, pagination and access URL generation\n   *",
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('buckets.get-file-metadata')
  async run(): Promise<void> {
    const { flags } = await this.parse(GetFileMetadata);
    const spinner = ora('Executing buckets get-file-metadata...').start();

    try {
      const client = await getSDKClient();
      const { 'folder-id': folderId, output, ...data } = flags;
      const result = await client.buckets.getFileMetaData(data as any, folderId);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
