/**
 * Auto-generated CLI Command: buckets get-read-uri
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.767Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../utils/sdk-client.js';
import { formatOutput } from '../../utils/output-formatter.js';
import { track } from '../../telemetry/index.js';

export default class GetReadUri extends Command {
  static description = "Gets a direct download URL for a file in the bucket";

  static examples = [
    'uipath buckets get-read-uri --options "example"'
  ];

  static flags = {
        'options': Flags.string({
      description: "Contains bucketId, folderId, file path and optional expiry time\n   *",
      required: true,
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('buckets.get-read-uri')
  async run(): Promise<void> {
    const { flags } = await this.parse(GetReadUri);
    const spinner = ora('Executing buckets get-read-uri...').start();

    try {
      const client = await getSDKClient();
      const { 'folder-id': folderId, output, ...data } = flags;
      const result = await client.buckets.getReadUri(data as any);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
