import type {
  SpanGetResponse,
  TracesGetByIdOptions,
} from './traces.types';

/**
 * Service for querying UiPath execution traces (spans).
 *
 * Traces are OpenTelemetry-compatible execution records generated by agents, robots,
 * Maestro processes, conversational agents, and other UiPath execution sources.
 * The `source` field on each {@link SpanGetResponse} identifies the originating platform.
 *
 * @example
 * ```typescript
 * import { UiPath } from '@uipath/uipath-typescript/core';
 * import { Traces } from '@uipath/uipath-typescript/traces';
 *
 * const sdk = new UiPath(config);
 * await sdk.initialize();
 *
 * const traces = new Traces(sdk);
 * const spans = await traces.getById('<traceId>');
 * ```
 */
export interface TracesServiceModel {
  /**
   * Gets all spans for a specific trace ID.
   *
   * Returns up to `pageSize` spans (default 1000) in a single fetch.
   * Accepts both GUID format and OTEL 32-char hex format — the API normalizes both.
   *
   * @param traceId - Trace identifier
   * @param options - Optional filters {@link TracesGetByIdOptions}
   * @returns Promise resolving to an array of {@link SpanGetResponse}
   * @example
   * ```typescript
   * import { Traces } from '@uipath/uipath-typescript/traces';
   *
   * const traces = new Traces(sdk);
   * const spans = await traces.getById('<traceId>');
   * console.log(spans.length, spans[0].spanType, spans[0].status);
   * ```
   * @example
   * ```typescript
   * // Filter to a specific agent's spans
   * const agentSpans = await traces.getById('<traceId>', {
   *   agentId: '<agentId>',
   *   pageSize: 500,
   * });
   * ```
   */
  getById(traceId: string, options?: TracesGetByIdOptions): Promise<SpanGetResponse[]>;

  /**
   * Gets specific spans by trace ID and span IDs.
   *
   * Accepts OTEL 16-char hex or GUID format for span IDs.
   *
   * @param traceId - Trace identifier
   * @param spanIds - List of span IDs to retrieve
   * @returns Promise resolving to an array of matching {@link SpanGetResponse}
   * @example
   * ```typescript
   * import { Traces } from '@uipath/uipath-typescript/traces';
   *
   * const traces = new Traces(sdk);
   *
   * // First retrieve all spans to find the IDs you want
   * const allSpans = await traces.getById('<traceId>');
   * const spanIds = allSpans.slice(0, 3).map(s => s.id);
   *
   * const subset = await traces.getSpansByIds('<traceId>', spanIds);
   * ```
   */
  getSpansByIds(traceId: string, spanIds: string[]): Promise<SpanGetResponse[]>;

}
