import type {
  SpanResponse,
  TracesGetByIdOptions,
  TracesGetByAgentIdOptions,
} from './traces.types';
import type { PaginatedResponse, NonPaginatedResponse, HasPaginationOptions } from '../../../utils/pagination';

/**
 * Service for querying UiPath execution traces (spans).
 *
 * Traces are OpenTelemetry-compatible execution records generated by agents, robots,
 * Maestro processes, conversational agents, and other UiPath execution sources.
 * The `source` field on each {@link SpanResponse} identifies the originating platform.
 *
 * @example
 * ```typescript
 * import { UiPath } from '@uipath/uipath-typescript/core';
 * import { Traces } from '@uipath/uipath-typescript/traces';
 *
 * const sdk = new UiPath(config);
 * await sdk.initialize();
 *
 * const traces = new Traces(sdk);
 * const spans = await traces.getById('<traceId>');
 * ```
 */
export interface TracesServiceModel {
  /**
   * Gets all spans for a specific trace ID.
   *
   * Returns up to `pageSize` spans (default 1000) in a single fetch.
   * Accepts both GUID format and OTEL 32-char hex format — the API normalizes both.
   *
   * @param traceId - Trace identifier
   * @param options - Optional filters {@link TracesGetByIdOptions}
   * @returns Promise resolving to an array of {@link SpanResponse}
   * @example
   * ```typescript
   * import { Traces } from '@uipath/uipath-typescript/traces';
   *
   * const traces = new Traces(sdk);
   * const spans = await traces.getById('<traceId>');
   * console.log(spans.length, spans[0].spanType, spans[0].status);
   * ```
   * @example
   * ```typescript
   * // Filter to a specific agent's spans
   * const agentSpans = await traces.getById('<traceId>', {
   *   agentId: '<agentId>',
   *   pageSize: 500,
   * });
   * ```
   */
  getById(traceId: string, options?: TracesGetByIdOptions): Promise<SpanResponse[]>;

  /**
   * Gets specific spans by trace ID and span IDs.
   *
   * Accepts OTEL 16-char hex or GUID format for span IDs.
   *
   * @param traceId - Trace identifier
   * @param spanIds - List of span IDs to retrieve
   * @returns Promise resolving to an array of matching {@link SpanResponse}
   * @example
   * ```typescript
   * import { Traces } from '@uipath/uipath-typescript/traces';
   *
   * const traces = new Traces(sdk);
   *
   * // First retrieve all spans to find the IDs you want
   * const allSpans = await traces.getById('<traceId>');
   * const spanIds = allSpans.slice(0, 3).map(s => s.id);
   *
   * const subset = await traces.getSpansByIds('<traceId>', spanIds);
   * ```
   */
  getSpansByIds(traceId: string, spanIds: string[]): Promise<SpanResponse[]>;

  /**
   * Gets spans grouped by agent ID, with optional time range filtering and pagination.
   *
   * When no pagination options are provided, returns all matching results as {@link NonPaginatedResponse}.
   * When pagination options are provided, returns a {@link PaginatedResponse}.
   *
   * @param agentId - Agent identifier (GUID)
   * @param options - Optional filters and pagination {@link TracesGetByAgentIdOptions}
   * @returns Promise resolving to paginated or non-paginated {@link SpanResponse} collection
   * @example
   * ```typescript
   * import { Traces } from '@uipath/uipath-typescript/traces';
   *
   * const traces = new Traces(sdk);
   * const history = await traces.getSpansByAgentId('<agentId>');
   * console.log(history.totalCount, history.items[0].startTime);
   * ```
   * @example
   * ```typescript
   * // Paginated with time filter
   * const page1 = await traces.getSpansByAgentId('<agentId>', {
   *   pageSize: 10,
   *   startTime: '2026-01-01T00:00:00Z',
   *   endTime: '2026-02-01T00:00:00Z',
   * });
   * if (page1.hasNextPage) {
   *   const page2 = await traces.getSpansByAgentId('<agentId>', { cursor: page1.nextCursor });
   * }
   * ```
   */
  getSpansByAgentId<T extends TracesGetByAgentIdOptions = TracesGetByAgentIdOptions>(
    agentId: string,
    options?: T
  ): Promise<
    T extends HasPaginationOptions<T>
      ? PaginatedResponse<SpanResponse>
      : NonPaginatedResponse<SpanResponse>
  >;

}
