import { BaseOptions, RequestOptions } from '../common/types';
import { PaginationOptions } from '../../utils/pagination';

/**
 * The type of the Machine.
 */
export enum MachineType {
  /** A standard machine mapped to a single host */
  Standard = 'Standard',
  /** A machine template that can match multiple hosts dynamically */
  Template = 'Template'
}

/**
 * The scope of the Machine.
 */
export enum MachineScope {
  /** Default scope for standard machines */
  Default = 'Default',
  /** Machine is shared across folders */
  Shared = 'Shared',
  /** Machine is scoped to a personal workspace */
  PersonalWorkspace = 'PersonalWorkspace',
  /** Cloud-hosted machine */
  Cloud = 'Cloud',
  /** Serverless machine */
  Serverless = 'Serverless',
  /** Automation Cloud Robot machine */
  AutomationCloudRobot = 'AutomationCloudRobot',
  /** Elastic Robot pool machine */
  ElasticRobot = 'ElasticRobot',
  /** Agent Service machine */
  AgentService = 'AgentService',
  /** Process Orchestration machine */
  ProcessOrchestration = 'ProcessOrchestration'
}

/**
 * The versions of the Robots hosted on the Machine.
 */
export interface MachineRobotVersion {
  /** The version of the Robot hosted on the Machine */
  version: string;
  /** The number of Robots on the Machine with the specified version */
  connectedRobotsCount: number;
}

/**
 * The Machine that hosts the Robot.
 */
export interface MachineGetResponse {
  /** An immutable unique identifier that is preserved during tenant migration */
  key: string;
  /** The name of the Machine a Robot is hosted on */
  name: string;
  /** The description of the Machine */
  description: string | null;
  /** The type of the Machine */
  type: MachineType;
  /** The scope of the Machine */
  scope: MachineScope;
  /** Number of NonProduction slots to be reserved at runtime */
  nonProductionSlots: number;
  /** Number of Unattended slots to be reserved at runtime */
  unattendedSlots: number;
  /** Number of Headless slots to be reserved at runtime */
  headlessSlots: number;
  /** Number of TestAutomation slots to be reserved at runtime */
  testAutomationSlots: number;
  /** The versions of the Robots hosted on the Machine */
  robotVersions: MachineRobotVersion[];
  /** Client secret generated by Identity Server. Use in combination with LicenseKey (ClientId) to connect robot */
  clientSecret: string;
  /** The key is automatically generated from the server for the Robot machine. For the robot to work, the same key must exist on both the robot and Orchestrator. All robots on a machine must have the same license key in order to register correctly. */
  licenseKey: string | null;
  /** The unique identifier of the Machine */
  id: number;
}

/**
 * Options for getting machines with optional filtering
 */
export type MachineGetAllOptions = RequestOptions & PaginationOptions;

/**
 * Options for getting a single machine by ID
 */
export type MachineGetByIdOptions = BaseOptions;
