/**
 * Auto-generated CLI Command: tasks assign
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.761Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../utils/sdk-client.js';
import { formatOutput } from '../../utils/output-formatter.js';
import { track } from '../../telemetry/index.js';

export default class Assign extends Command {
  static description = "Assigns tasks to users";

  static examples = [
    'uipath tasks assign --task-assignments "example"'
  ];

  static flags = {
        'task-assignments': Flags.string({
      description: "Single task assignment or array of task assignments\n   *",
      required: true,
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('tasks.assign')
  async run(): Promise<void> {
    const { flags } = await this.parse(Assign);
    const spinner = ora('Executing tasks assign...').start();

    try {
      const client = await getSDKClient();
      const { 'folder-id': folderId, output, ...data } = flags;
      const result = await client.tasks.assign(data as any);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
