/**
 * Auto-generated CLI Command: tasks create-and-assign-task
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.768Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../utils/sdk-client.js';
import { formatOutput } from '../../utils/output-formatter.js';
import { track } from '../../telemetry/index.js';

export default class CreateAndAssignTask extends Command {
  static description = "Creates a task and immediately assigns it to a user";

  static examples = [
    'uipath tasks create-and-assign-task'
  ];

  static flags = {
        'task': Flags.string({
      description: "Task data to create",
      required: true,
    }),
    'folder-id': Flags.integer({
      description: "Folder ID",
      required: true,
    }),
    'user-id': Flags.string({
      description: "User ID to assign the task to",
      required: true,
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('tasks.create-and-assign-task')
  async run(): Promise<void> {
    const { flags } = await this.parse(CreateAndAssignTask);
    const spinner = ora('Executing tasks create-and-assign-task...').start();

    try {
      const client = await getSDKClient();
      const createdTask = await client.tasks.create(flags['task'], flags['folder-id']);
      const step2Result = await client.tasks.assign({"taskAssignments":[{"taskId":"createdTask.id","userId":"userId"}]});
      const result = createdTask;

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
