/**
 * Auto-generated CLI Command: tasks create
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.759Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../utils/sdk-client.js';
import { formatOutput } from '../../utils/output-formatter.js';
import { track } from '../../telemetry/index.js';

export default class Create extends Command {
  static description = "Create a new Action Center task for human-in-the-loop workflows";

  static examples = [
    'uipath tasks create --task "example" --folder-id "123"'
  ];

  static flags = {
        'task': Flags.string({
      description: "to be created\n   *",
      required: true,
    }),
    'folder-id': Flags.integer({
      description: "Required folder ID\n   *",
      required: true,
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('tasks.create')
  async run(): Promise<void> {
    const { flags } = await this.parse(Create);
    const spinner = ora('Executing tasks create...').start();

    try {
      const client = await getSDKClient();
      const { 'folder-id': folderId, output, ...data } = flags;
      const result = await client.tasks.create(data as any, folderId);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
