/**
 * Auto-generated CLI Command: tasks get-users
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.760Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../utils/sdk-client.js';
import { formatOutput } from '../../utils/output-formatter.js';
import { track } from '../../telemetry/index.js';

export default class GetUsers extends Command {
  static description = "Gets users in the given folder who have Tasks.View and Tasks.Edit permissions\n\nThe method returns either:\n- An array of users (when no pagination parameters are provided)\n- A paginated result with navigation cursors (when any pagination parameter is provided)";

  static examples = [
    'uipath tasks get-users --folder-id "123"'
  ];

  static flags = {
        'folder-id': Flags.integer({
      description: "The folder ID to get users from\n   *",
      required: true,
    }),
    'options': Flags.string({
      description: "Optional query and pagination parameters\n   *",
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('tasks.get-users')
  async run(): Promise<void> {
    const { flags } = await this.parse(GetUsers);
    const spinner = ora('Executing tasks get-users...').start();

    try {
      const client = await getSDKClient();
      const { 'folder-id': folderId, output, ...data } = flags;
      const result = await client.tasks.getUsers(data as any, folderId);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
