/**
 * Auto-generated CLI Command: tasks list
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.760Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../utils/sdk-client.js';
import { formatOutput } from '../../utils/output-formatter.js';
import { track } from '../../telemetry/index.js';

export default class List extends Command {
  static description = "Gets tasks across folders with optional filtering and folder scoping\n\nThe method returns either:\n- An array of tasks (when no pagination parameters are provided)\n- A paginated result with navigation cursors (when any pagination parameter is provided)";

  static examples = [
    'uipath tasks list'
  ];

  static flags = {
        'options': Flags.string({
      description: "*",
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('tasks.list')
  async run(): Promise<void> {
    const { flags } = await this.parse(List);
    const spinner = ora('Executing tasks list...').start();

    try {
      const client = await getSDKClient();
      const result = await client.tasks.getAll(flags as any);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
