/**
 * Auto-generated CLI Command: entities update-records
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.762Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../utils/sdk-client.js';
import { formatOutput } from '../../utils/output-formatter.js';
import { track } from '../../telemetry/index.js';

export default class UpdateRecords extends Command {
  static description = "Updates data in an entity by entity ID";

  static examples = [
    'uipath entities update-records --id "example" --data "example"'
  ];

  static flags = {
        'id': Flags.string({
      description: "id parameter",
      required: true,
    }),
    'data': Flags.string({
      description: "Array of records to update. Each record MUST contain the record Id,\n   *               otherwise the update will fail.\n   *",
      required: true,
    }),
    'options': Flags.string({
      description: "*",
      default: "{}",
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('entities.update-records')
  async run(): Promise<void> {
    const { flags } = await this.parse(UpdateRecords);
    const spinner = ora('Executing entities update-records...').start();

    try {
      const client = await getSDKClient();
      const { 'folder-id': folderId, output, ...data } = flags;
      const result = await client.entities.updateById(data as any);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
