/**
 * Auto-generated CLI Command: maestro case-instances action-tasks
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.764Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../../utils/sdk-client.js';
import { formatOutput } from '../../../utils/output-formatter.js';
import { track } from '../../../telemetry/index.js';

export default class ActionTasks extends Command {
  static description = "Get human in the loop tasks associated with a case instance";

  static examples = [
    'uipath maestro case-instances action-tasks --case-instance-id "example"'
  ];

  static flags = {
        'case-instance-id': Flags.string({
      description: "The ID of the case instance\n   *",
      required: true,
    }),
    'options': Flags.string({
      description: "*",
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('maestro case-instances.action-tasks')
  async run(): Promise<void> {
    const { flags } = await this.parse(ActionTasks);
    const spinner = ora('Executing maestro case-instances action-tasks...').start();

    try {
      const client = await getSDKClient();
      const { 'folder-id': folderId, output, ...data } = flags;
      const result = await client.maestro.cases.instances.getActionTasks(data as any);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
