/**
 * Auto-generated CLI Command: maestro instances execution-history
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.765Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../../utils/sdk-client.js';
import { formatOutput } from '../../../utils/output-formatter.js';
import { track } from '../../../telemetry/index.js';

export default class ExecutionHistory extends Command {
  static description = "Get execution history (spans) for a process instance";

  static examples = [
    'uipath maestro instances execution-history --instance-id "example"'
  ];

  static flags = {
        'instance-id': Flags.string({
      description: "The ID of the instance to get history for\n   *",
      required: true,
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('maestro instances.execution-history')
  async run(): Promise<void> {
    const { flags } = await this.parse(ExecutionHistory);
    const spinner = ora('Executing maestro instances execution-history...').start();

    try {
      const client = await getSDKClient();
      const { 'folder-id': folderId, output, ...data } = flags;
      const result = await client.maestro.processes.instances.getExecutionHistory(data as any);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
