/**
 * Auto-generated CLI Command: maestro instances get
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.765Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../../utils/sdk-client.js';
import { formatOutput } from '../../../utils/output-formatter.js';
import { track } from '../../../telemetry/index.js';

export default class Get extends Command {
  static description = "Get a process instance by ID with operation methods (cancel, pause, resume)";

  static examples = [
    'uipath maestro instances get --id "example" --folder-key "example"'
  ];

  static flags = {
        'id': Flags.string({
      description: "The ID of the instance to retrieve\n   *",
      required: true,
    }),
    'folder-key': Flags.string({
      description: "The folder key for authorization\n   *",
      required: true,
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('maestro instances.get')
  async run(): Promise<void> {
    const { flags } = await this.parse(Get);
    const spinner = ora('Executing maestro instances get...').start();

    try {
      const client = await getSDKClient();
      const result = await client.maestro.processes.instances.getById(flags.id, flags['folder-key']);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
