/**
 * Auto-generated CLI Command: maestro instances list
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.764Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../../utils/sdk-client.js';
import { formatOutput } from '../../../utils/output-formatter.js';
import { track } from '../../../telemetry/index.js';

export default class List extends Command {
  static description = "Get all process instances with optional filtering and pagination\n\nThe method returns either:\n- A NonPaginatedResponse with items array (when no pagination parameters are provided)\n- A PaginatedResponse with navigation cursors (when any pagination parameter is provided)";

  static examples = [
    'uipath maestro instances list'
  ];

  static flags = {
        'options': Flags.string({
      description: "Query parameters for filtering instances and pagination\n   *",
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('maestro instances.list')
  async run(): Promise<void> {
    const { flags } = await this.parse(List);
    const spinner = ora('Executing maestro instances list...').start();

    try {
      const client = await getSDKClient();
      const result = await client.maestro.processes.instances.getAll(flags as any);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
