/**
 * Auto-generated CLI Command: assets get
 *
 * This file is generated by the CLI command generator.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated at: 2025-12-16T21:17:45.766Z
 * To regenerate: npm run generate
 */

import { Command, Flags } from '@oclif/core';
import chalk from 'chalk';
import ora from 'ora';
import { getSDKClient } from '../../utils/sdk-client.js';
import { formatOutput } from '../../utils/output-formatter.js';
import { track } from '../../telemetry/index.js';

export default class Get extends Command {
  static description = "Gets a single asset by ID";

  static examples = [
    'uipath assets get --id "123" --folder-id "123"'
  ];

  static flags = {
        'id': Flags.integer({
      description: "Asset ID\n   *",
      required: true,
    }),
    'folder-id': Flags.integer({
      description: "Required folder ID\n   *",
      required: true,
    }),
    'options': Flags.string({
      description: "Optional query parameters (expand, select)\n   *",
      default: "{}",
    }),
    output: Flags.string({
      char: 'o',
      description: 'Output format (json, table, yaml)',
      options: ['json', 'table', 'yaml'],
      default: 'table'
    })
  };

  @track('assets.get')
  async run(): Promise<void> {
    const { flags } = await this.parse(Get);
    const spinner = ora('Executing assets get...').start();

    try {
      const client = await getSDKClient();
      const result = await client.assets.getById(flags.id);

      spinner.succeed('Operation completed');
      this.log(formatOutput(result, flags.output as 'json' | 'table' | 'yaml'));
    } catch (error) {
      spinner.fail('Operation failed');
      this.log(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      this.exit(1);
    }
  }
}
