name: Deploy Documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  actions: write
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Node Dependencies
        run: |
          npm ci

      - name: Setup Python Virtual Environment
        run: |
          python3 -m venv docs-env
          source docs-env/bin/activate
          pip install -r docs/requirements.txt

      - name: Generate API Documentation
        run: npm run docs:api

      - name: Build MkDocs Documentation
        run: |
          source docs-env/bin/activate
          mkdocs build

      - name: Deploy to GitHub Pages
        run: |
          source docs-env/bin/activate
          mkdocs gh-deploy --force